name: Upload Jenkins Artifacts

on:
  push:
    branches:
      - main

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Workspace Contents
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jenkins-artifacts
          path: |
            reactattifact/android/build.gradle
