name: Upload Jenkins Artifacts

on:
  push:
    branches:
      - master

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Navigate to Source Code Directory
        run: cd /var/lib/jenkins/workspace/reactattifact/android

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jenkins-artifacts
          path: |
            gradlew
